apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "KEBAB_NAME.fullname" . }}
data:
  AzureWebJobsStorage: '{AzureWebJobsStorage}'
  AzureWebJobsSecretStorageType: files
  FUNCTIONS_WORKER_RUNTIME: dotnet
