{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "KEBAB_NAME.serviceAccountName" . }}
  labels:
{{ include "KEBAB_NAME.labels" . | nindent 4 }}
{{- end -}}
